import { INSTRUCTION_SYNTAX_PATTERN } from "~/constants/instruction";

export const EDITOR_CONSTANTS = {
  BLUR_TIMEOUT_MS: 100,
  CONTENT_SYNC_TIMEOUT_MS: 0,
  MAX_IMAGE_SIZE: 10 * 1024 * 1024,
  FONT_SIZE_VALUES: ["0.75em", "1em", "1.5em", "2.5em"],
  COLOR_PALETTE: [
    "#000000",
    "#e60000",
    "#ff9900",
    "#ffff00",
    "#008a00",
    "#0066cc",
    "#9933ff",
    "#ffffff",
    "#facccc",
    "#ffebcc",
    "#ffffcc",
    "#cce8cc",
    "#cce0f5",
    "#ebd6ff",
    "#bbbbbb",
    "#f06666",
    "#ffc266",
    "#ffff66",
    "#66b966",
    "#66a3e0",
    "#c285ff",
    "#888888",
    "#a10000",
    "#b26b00",
    "#b2b200",
    "#006100",
    "#0047b2",
    "#6b24b2",
    "#444444",
    "#5c0000",
    "#663d00",
    "#666600",
    "#003700",
    "#002966",
    "#3d1466",
  ],

  EMPTY_PARAGRAPH_HTML: "<p></p>",
  PARAGRAPH_MARGIN_STYLE: "margin: 0;",

  EDITOR_CLASS: "tiptap-editor",
  EDITOR_WRAPPER_CLASS: "tiptap-wrapper",
  EDITOR_FOCUSED_CLASS: "tiptap-focused",
  LINK_CLASS: "tiptap-link",
  IMAGE_CLASS: "tiptap-image",
  CONTENT_EDITOR_CLASS: "content-editor",
  RTL_CLASS: "rtl",
  LTR_CLASS: "ltr",

  TOOLBAR_CLASS: "tiptap-toolbar",
  TOOLBAR_BUTTON_CLASS: "tiptap-toolbar-button",
  COLLAPSIBLE_CLASS: "tiptap-collapsible",
};

export const PREVENT_ENTER_EXTENSION = {
  NAME: "preventEnter",
  LOG_PREFIX: "[PreventEnterExtension]",
  ERROR_MESSAGES: {
    SAVING_CONTENT: "Error saving content:",
    NEW_LINE_CALLBACK: "Error in onNewLine callback:",
  },
};

export const INSTRUCTION_EDITOR_CONFIG = {
  PATTERN: INSTRUCTION_SYNTAX_PATTERN,
  SELECTORS: {
    HIGHLIGHT_CLASS: "instruction-highlight",
    HIGHLIGHT: ".instruction-highlight",
    TOOLTIP_TARGETS: ".instruction-highlight [data-tooltip]",
  },
  TOOLTIP: {
    delay: [0, 0],
    duration: [200, 150],
    placement: "auto",
    theme: "instruction",
    arrow: true,
    maxWidth: 400,
    interactive: false,
    appendTo: document.body,
    ignoreAttributes: true,
  },
};
