// Icon sets the icon picker searches. Picked icons are uploaded and served as
// survey resources, so each set's license applies to Qlarr. Every license was
// checked against the set's own repo, npm package or Figma Community page, not
// Iconify's metadata, which is wrong for some sets (css.gg, Unicons, Reicon).

// Free for commercial use, no visible credit needed.
const NO_CREDIT_ICON_PREFIXES = [
  // MIT
  "akar-icons",
  "ant-design",
  "at-icons",
  "bi",
  "boxicons",
  "bx",
  "bxs",
  "bytesize",
  "charm",
  "circle-flags",
  "clarity",
  "codex",
  "dinkie-icons",
  "duo-icons",
  "ei",
  "eos-icons",
  "ep",
  "f7",
  "famicons",
  "fe",
  "flag",
  "flagpack",
  "flowbite",
  "fluent",
  "fluent-color",
  "fluent-emoji-flat",
  "fluent-emoji-high-contrast",
  "formkit",
  "geo",
  "ginetex",
  "glyphs",
  "glyphs-poly",
  "gravity-ui",
  "griddy-icons",
  "healthicons",
  "heroicons",
  "hugeicons",
  "humbleicons",
  "iconmind",
  "iconoir",
  "ion",
  "ix",
  "jam",
  "keyline-icons",
  "line-md",
  "lineicons",
  "lsicon",
  "majesticons",
  "medical-icon",
  "meteocons",
  "meteor-icons",
  "mi",
  "mynaui",
  "nimbus",
  "octicon",
  "ooui",
  "pajamas",
  "ph",
  "pixelarticons",
  "prime",
  "proicons",
  "qlementine-icons",
  "quill",
  "radix-icons",
  "si",
  "sidekickicons",
  "stash",
  "svg-spinners",
  "tabler",
  "tdesign",
  "teenyicons",
  "uiw",
  "vadivam",
  "weui",
  "zondicons",
  // ISC
  "lucide",
  "lucide-lab",
  // Apache 2.0 (noto and noto-v1: the image files)
  "carbon",
  "cuida",
  "garden",
  "ic",
  "icon-park",
  "icon-park-outline",
  "icon-park-solid",
  "icon-park-twotone",
  "mage",
  "material-symbols",
  "material-symbols-light",
  "mdi",
  "memory",
  "mingcute",
  "noto",
  "noto-v1",
  "oui",
  // CC0
  "cif",
  "maki",
  "osmic",
  "pinhead",
  "temaki",
  // Unlicense
  "system-uicons",
  // BSD 3-Clause
  "rivet-icons",
  // Remix Icon License: allows use inside apps, bans reselling the icons on their own
  "ri",
];

const CC_BY_4 = {
  name: "CC BY 4.0",
  url: "https://creativecommons.org/licenses/by/4.0/",
};

// Free for commercial use, but CC BY requires a credit line for each set (name,
// author, link, license) somewhere users can find it, such as a credits page.
export const CREDITED_ICON_SETS = [
  {
    name: "Solar",
    author: "480 Design",
    url: "https://www.figma.com/community/file/1166831539721848736",
    license: CC_BY_4,
    prefixes: ["solar"],
  },
  {
    // Streamline's license asks for the credit to link to streamlinehq.com.
    name: "Streamline free icons",
    author: "Streamline",
    url: "https://www.streamlinehq.com",
    license: CC_BY_4,
    prefixes: [
      "streamline",
      "streamline-block",
      "streamline-color",
      "streamline-cyber",
      "streamline-cyber-color",
      "streamline-emojis",
      "streamline-flex",
      "streamline-flex-color",
      "streamline-freehand",
      "streamline-freehand-color",
      "streamline-kameleon-color",
      "streamline-pixel",
      "streamline-plump",
      "streamline-plump-color",
      "streamline-sharp",
      "streamline-sharp-color",
      "streamline-stickies-color",
      "streamline-ultimate",
      "streamline-ultimate-color",
      "guidance",
      "covid",
    ],
  },
  {
    name: "Font Awesome Free",
    author: "Fonticons, Inc.",
    url: "https://fontawesome.com",
    license: CC_BY_4,
    prefixes: ["fa7-solid", "fa7-regular"],
  },
  {
    name: "Twemoji",
    author: "Twitter, Inc. and other contributors",
    url: "https://github.com/jdecked/twemoji",
    license: CC_BY_4,
    prefixes: ["twemoji"],
  },
  {
    name: "Emoji One",
    author: "Emoji One",
    url: "https://github.com/EmojiTwo/emojitwo",
    license: CC_BY_4,
    prefixes: ["emojione", "emojione-monotone"],
  },
  {
    name: "Röntgen",
    author: "Sergey Vartanov",
    url: "https://github.com/enzet/Roentgen",
    license: CC_BY_4,
    prefixes: ["roentgen"],
  },
  {
    name: "Font-GIS",
    author: "Jean-Marc Viglino",
    url: "https://github.com/viglino/font-gis",
    license: CC_BY_4,
    prefixes: ["gis"],
  },
  {
    name: "FontAudio",
    author: "fefanto",
    url: "https://github.com/fefanto/fontaudio",
    license: CC_BY_4,
    prefixes: ["fad"],
  },
  {
    name: "CoreUI Icons Free",
    author: "creativeLabs Łukasz Holeczek",
    url: "https://github.com/coreui/coreui-icons",
    license: CC_BY_4,
    prefixes: ["cil"],
  },
  {
    name: "Lets Icons",
    author: "Leonid Tsvetkov",
    url: "https://www.figma.com/community/file/886554014393250663",
    license: CC_BY_4,
    prefixes: ["lets-icons"],
  },
  {
    name: "Basil",
    author: "Craftwork",
    url: "https://www.figma.com/community/file/931906394678748246",
    license: CC_BY_4,
    prefixes: ["basil"],
  },
  {
    name: "Pixel Icon Library",
    author: "HackerNoon",
    url: "https://github.com/hackernoon/pixel-icon-library",
    license: CC_BY_4,
    prefixes: ["pixel"],
  },
  {
    name: "coolicons",
    author: "Kryston Schwarze",
    url: "https://github.com/krystonschwarze/coolicons",
    license: CC_BY_4,
    prefixes: ["ci"],
  },
  {
    name: "Pepicons",
    author: "CyCraft",
    url: "https://github.com/CyCraft/pepicons",
    license: CC_BY_4,
    prefixes: ["pepicons-pop", "pepicons-print", "pepicons-pencil"],
  },
  {
    name: "NRK Core Icons",
    author: "Norsk rikskringkasting (NRK)",
    url: "https://github.com/nrkno/core-icons",
    license: CC_BY_4,
    prefixes: ["nrk"],
  },
  {
    name: "Codicons",
    author: "Microsoft Corporation",
    url: "https://github.com/microsoft/vscode-codicons",
    license: CC_BY_4,
    prefixes: ["codicon"],
  },
  {
    // Iconify labels this Apache 2.0, but that covers only the code; the
    // artwork is CC BY 4.0.
    name: "Firefox OS Emoji",
    author: "Mozilla",
    url: "https://github.com/mozilla/fxemoji",
    license: CC_BY_4,
    prefixes: ["fxemoji"],
  },
];

export const ALLOWED_ICON_PREFIXES = [
  ...NO_CREDIT_ICON_PREFIXES,
  ...CREDITED_ICON_SETS.flatMap((set) => set.prefixes),
];
